### ISSUE TITLE
Fixed button is missing

### ISSUE THREAD

**Issue by creold** [Gifox/Tracker#236]
On iMac with High Sierra 10.13.6, the Fixed button with the lock icon was missing from the "Free area selection". This happened after updating to version 2.3.1, where the license issue was fixed. I tried reinstalling the application with the /Library folders cleared. On macOS Monterey, the button is still there
![fixed-button](https://user-images.githubusercontent.com/32217031/162167011-e8880e63-aeda-412e-bce9-d4fc87c4a8f8.jpg)

**Comment by iby** [comment]
Hmmm. This is a long-time floater bug – we've seen it in the past, but not lately, and I was under impression that this is resolved… ☹️

Out of interest, can you try the older [2.2.5 version](https://distribution-absf.s3-eu-central-1.amazonaws.com/gifox/020205.01.dmg) on High Sierra? Does that appear as expected?

**Comment by iby** [comment]
Hey @creold, I'm doing some housekeeping and we haven't seen this issue for awhile now. It seemed to be related to certain OS and hardware versions, but we weren't able to reproduce it locally to understand what exactly is causing this.

I'm going to close this down, but wanted to also check if this is still happening for anyone? 🙏

**Comment by creold** [comment]
Yep. It probably has to do with the operating system and some other parameters. Because on the old iMac with High Sierra the button is still missing in Gifox v2.6.1, but on the Macbook with OS Monterey it is there. But I'm already used to it, knowing that all you have to do is click on the empty area, because the button is actually there, even if it's invisible :-)
